project_id = "fjtwjcnfsghcbgomepdm"

[functions.isp-api]
verify_jwt = false

[functions.network-sync]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.auto-suspend]
verify_jwt = false
